Финальное задание
GolovkoStepan/test_guru pull request #30
Opened 2020-10-31 15:22 UTC by GolovkoStepan

2020-10-31 21:09 UTC, VidgarVii requested changes

2020-10-31 21:09 UTC, VidgarVii commented on app/services/badges_service.rb
> +    statistics      = statistics.where('statistics.created_at > :date', date: last_issue_date) if last_issue_date
для формировании statistics можно выделить метод который спрячит этот ужасный длинный запрос. Этот же метод можно будет использовать в #all_by_category?() со своими аргументами

2020-10-31 21:09 UTC, VidgarVii commented on app/models/issued_badge.rb
> +class IssuedBadge < ApplicationRecord
мне кажеться в полне хватило бы связи хабтм м/у юзером и баджами

2020-11-01 03:55 UTC, GolovkoStepan commented on app/services/badges_service.rb
> +      respond_to?(rule_method) && send(rule_method, badge.rule_value) ? badge : nil
Потому что существуют всякие штуки типа update_attribute, update_column, (validation: false)
Чтобы спалось крепче)

2020-11-01 03:56 UTC, GolovkoStepan commented on app/services/badges_service.rb
> +  def rule_to_method_name(rule)
Ну вообще, да. Метод не особо тут нужен

2020-11-01 04:05 UTC, GolovkoStepan commented on app/models/statistic.rb
>      current_question.correct_answers.ids.sort == Array(answer_ids).map(&:to_i).sort
Да я бы не сказал))) Я видел модельки и по умнее, строчек так на 1000
Кмк вся эта котовасия с определением правильности прохождения тут и должна быть, а если делать отдельный класс, то какой? TestCompleteService? В который мы передадим этот statistics и параметры чтобы он там что-то делал и в итоге у нас будет завершенный или нет успешно тест? Ну, не знаю...

2020-11-01 04:11 UTC, GolovkoStepan commented on config/cable.yml
> +  adapter: redis
Опа, ну тут я не согласен. Во первых, редис нужен для sidekiq, поэтому ставить его придется полюбому. Во вторых, как по мне, лучше уж чтобы это все работало наиболее приближенно к боевым условиям. Не говоря уже о том, что установка редиса занимает несколько минут, не вижу тут проблем

2020-11-01 04:20 UTC, GolovkoStepan commented on app/models/issued_badge.rb
> +class IssuedBadge < ApplicationRecord
Ну да, я так и сделал сначала. Но у связанной таблицы не было timestamps, да и вообще - has_many through по прикольней. Сегодня нам надо просто связать награды и пользователей, а завтра надо еще ченить фиксировать. 
Лучше уж сразу быть готовым к "непредвиденным последствиям"
![image](https://user-images.githubusercontent.com/33656109/97795059-807c6080-1c23-11eb-9ed1-02a4b4daabd0.png)

2020-11-01 04:24 UTC, GolovkoStepan commented on app/services/badges_service.rb
> +  RULES = %w[one_try all_by_level all_by_category].freeze
Ну вот((((((( Я сначала так и сделал!! Но мне Максим посоветовал вынести в сервис
<img width="809" alt="Снимок экрана 2020-11-01 в 09 22 22" src="https://user-images.githubusercontent.com/33656109/97795086-d51fdb80-1c23-11eb-9459-4931b2865534.png">
Нам нужно синхронизироваться :)

2020-11-01 04:26 UTC, GolovkoStepan commented on app/services/badges_service.rb
> +  def give_the_user
Мне кажется, из названия класса мы можем догадаться)

2020-11-01 04:27 UTC, GolovkoStepan commented on app/models/statistic.rb
>      success_rate >= 85
Вот тут даже и возразить нечего

2020-11-01 04:28 UTC, GolovkoStepan commented on app/controllers/tests_controller.rb
> +    @tests = Test.all.page(params[:page])
Это стоит поправить

2020-11-01 04:31 UTC, GolovkoStepan commented on app/services/badges_service.rb
> +    statistics      = statistics.where('statistics.created_at > :date', date: last_issue_date) if last_issue_date
Да, я хотел сделать универсальный метод сначала, чтобы не копипастить это все. Но чет поленился) Особого профита тут просто я не вижу, разве что выйдет новое какое-то правило для наград

2020-11-01 04:35 UTC, GolovkoStepan commented on app/services/badges_service.rb
> +  private
А черт его знает) Вообще, да

2020-11-01 04:39 UTC, GolovkoStepan commented on app/models/issued_badge.rb
> +  after_create :notify_user
Все говорят, что колбеки это плохо, но все равно их юзают)
Ну кстати да, нотификация должна быть в контроллере, тут она смотрится не оч. У меня точно были мысли перенести это дело после проверки

2020-11-01 04:44 UTC, GolovkoStepan commented on app/services/badges_service.rb
> +  RULES = %w[one_try all_by_level all_by_category].freeze
А кстати, на счет enum. Прикольная тема, но он тут нам создаст методы типа all_by_category! или all_by_level?
Ну, такое.... 

Однако, enum я юзал в модели user - вот там это действительно полезно

2020-11-01 12:22 UTC, VidgarVii commented on app/services/badges_service.rb
> +  RULES = %w[one_try all_by_level all_by_category].freeze
ну создаст методы предикаты, ни чего страшного. 
Главное чтобы логика лежала в 1 месте. логика валидации у тебя сейчас разбросана м/у сервисом и моделью. А логика давать бадж или нет. Должна вся находиться в сервисе. Тогда вопрос к тебе. А нужна ли валидация правил в модели? Если нужна. То константа должна лежать в модели. Так как валидатор обращается к этой константе. Если константа нужна только для построении логики выдачи баджа. То оставляй константу в сервисе. Но тогда надо убирать связь м/у сервисом и моделью при создании баджа

2020-11-01 12:23 UTC, VidgarVii commented on app/services/badges_service.rb
> +      respond_to?(rule_method) && send(rule_method, badge.rule_value) ? badge : nil
respond_to?(rule_method) у тебя вызывается в контексте сервиса, а не модели. При чем тут валидация модели?

2020-11-01 12:25 UTC, VidgarVii commented on app/services/badges_service.rb
> +  def give_the_user
Степан, студент. Наверное хочет стать хорошим программистом. 
Я обращаюсь к Степану.  - Степан, дай Максу..  
Резонный вопрос. Что дать?

2020-11-01 12:29 UTC, VidgarVii commented on app/models/statistic.rb
>      current_question.correct_answers.ids.sort == Array(answer_ids).map(&:to_i).sort
модель AR ни когда не должна сожеражить в себе бизнес логику.

2020-11-01 12:31 UTC, VidgarVii commented on app/models/issued_badge.rb
> +class IssuedBadge < ApplicationRecord
не стоит охватывать сразу все кейсы. Придерживайся рамок поставленной задачи. Просто код должен быть легко расширяем. Тогда не будет проблем к появлениям новых условий

2020-11-01 12:57 UTC, VidgarVii requested changes

2020-11-01 12:57 UTC, VidgarVii commented on app/services/badges_service.rb
> +      rule_method    = "#{badge.rule}?".to_sym
в символ  не обязательно переводить

2020-11-01 12:57 UTC, VidgarVii commented on app/services/badges_service.rb
>        @current_badge = badge
инстанс переменная  для такого кейса не очень хороший выбор для построения логики. Нарушает идиомы ООП. При обращении к объекту класса можно будет увидеть новое свойство текущего баджа. Чего?) Передавай лушче этот текущий бадж аргументом, так как он нужен только выполнения каких-то внутренних задач

2020-11-01 12:57 UTC, VidgarVii commented on app/services/badges_service.rb
> +      send(rule_method, badge.rule_value) ? badge : nil
опять этот тернарник и nil... 

У многих разработчиков аллергия на нил. Так как одна из частых ошибка undefined method for NilClass. Старайся строить логику без нилов

2020-11-01 12:57 UTC, VidgarVii commented on app/services/badges_service.rb
> +      send(rule_method, badge.rule_value) ? badge : nil
используй select вместо map

2020-11-01 14:37 UTC, GolovkoStepan commented on app/services/badges_service.rb
> +      respond_to?(rule_method) && send(rule_method, badge.rule_value) ? badge : nil
Я к тому, что правило может оказаться не то. Можно создать модель пропуская валидации, ну и в сенд попадет не то. Вообщем, не важно, я это уже убрал енивей

2020-11-01 14:39 UTC, GolovkoStepan commented on app/services/badges_service.rb
> +  RULES = %w[one_try all_by_level all_by_category].freeze
Как сделать то в итоге?

2020-11-01 14:39 UTC, GolovkoStepan commented on app/services/badges_service.rb
> +  def give_the_user
Уже исправлено

2020-11-01 14:40 UTC, GolovkoStepan commented on app/models/issued_badge.rb
> +class IssuedBadge < ApplicationRecord
Ну по тз не было конкретных инструкций как именно делать это, поэтому уходит на мое усмотрение

2020-11-01 14:48 UTC, GolovkoStepan commented on app/services/badges_service.rb
> +      send(rule_method, badge.rule_value) ? badge : nil
От нила в руби никуда не денешься, насущная тема. А про замену на селект согласен, спс), просто привык уже мап и компакт для подобных дел юзать...

2020-11-07 13:57 UTC, merged